# CircleCI configuration file
version: 2.1

jobs:
  docker_build:
    machine:
      - image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: docker build -t app .

workflows:
  build:
    # List of jobs that will run
    jobs:
      - docker_build
