# CircleCI configuration file
version: 2.1

jobs:
  docker_build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: 
          name: Build and Run Contener
          command: docker build -t nodeapp .
      - run:
          name: Start conteneur
          command: docker run -dp 5000:5000 nodeapp
      - run: 
          name: Test 
          command: wget http://127.0.0.1:5000
      - run:
          name: Docker tag
          command: |
            docker login -u $username -p $password
            docker push nodeapp



workflows:
  build:
    # List of jobs that will run
    jobs:
      - docker_build
