# CircleCI configuration file
version: 2.1

jobs:
  docker_build:
    steps:
      - run: echo "Say goodbye to YAML!"

workflows:
  # Name of workflow
  build:
    # List of jobs that will run
    jobs:
      - docker_build
