# CircleCI configuration file
version: 2.1

jobs:
  docker_build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run: docker build -t app .

workflows:
  # Name of workflow
  build:
    # List of jobs that will run
    jobs:
      - docker_build
