# CircleCI configuration file
version: 2.1

jobs:
  docker_build:
    working_directory: /node-js-sample/
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run: docker build -t app .

workflows:
  build:
    # List of jobs that will run
    jobs:
      - docker_build
