# CircleCI configuration file
version: 2.1

jobs:
  docker_build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: 
          name: Build and Run Contener
          command: |
            docker build -t app . \
            docker run -p 5000:5000 app \
            wget http://127.0.0.1:5000


workflows:
  build:
    # List of jobs that will run
    jobs:
      - docker_build
